// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// get_mimetype
DataFrame get_mimetype(CharacterVector path);
RcppExport SEXP filemagic_get_mimetype(SEXP pathSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< CharacterVector >::type path(pathSEXP);
    __result = Rcpp::wrap(get_mimetype(path));
    return __result;
END_RCPP
}
