// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// incant
DataFrame incant(CharacterVector path);
RcppExport SEXP wand_incant(SEXP pathSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< CharacterVector >::type path(pathSEXP);
    __result = Rcpp::wrap(incant(path));
    return __result;
END_RCPP
}
