# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Retrieve 'magic' attributes from files and directories
#'
#' @param path character vector of files to use magic on
#' @return a \code{tibble} / \code{data.frame} of file magic attributes.
#'   Specifically, mime type, encoding, possible file extensions and
#'   type description are returned as colums in the data frame along
#'   with \code{path}.
#' @export
#' @examples
#' library(magrittr)
#' library(dplyr)
#'
#' system.file("img", package="filemagic") %>%
#'   list.files(full.names=TRUE) %>%
#'   incant() %>%
#'   glimpse()
incant <- function(path) {
    .Call('wand_incant', PACKAGE = 'wand', path)
}

